// Try-Catch: The try statement allows you to define a block of code to be tested for error while it is being executed.
// The catch statement allows you to define a block of code to be execute, if an error occurs in the try block.

// console.log("hello");
// console.log("hello");
// // let a = 5
// try{console.log(a);
// }
// catch(err)
// {
//   console.log("Caught an error...a is not defined");
//   console.log(err);
// }
// console.log("hello2");
